export const BOOKS = 'BOOKS'
export const COMICS = 'COMICS'
export const MOVIES = 'MOVIES'
export const MUSIC = 'MUSIC'
export const PODCASTS = 'PODCASTS'
export const TV = 'TV'

export const REQUEST_MOVIES = 'REQUEST_MOVIES'
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES'
export const FILTER_MOVIES = 'FILTER_MOVIES'
export const SORT_MOVIES = 'SORT_MOVIES'

export const REQUEST_MUSIC = 'REQUEST_MUSIC'
export const RECEIVE_MUSIC = 'RECEIVE_MUSIC'
export const FILTER_MUSIC = 'FILTER_MUSIC'
export const SORT_MUSIC = 'SORT_MUSIC'
